### ISSUE TITLE
Write TeleopDrive command class (NEO + SPARK MAX)

### ISSUE THREAD

**Issue by tylertian123** [Arctos6135/frc-2020#11]
Write code for the `TeleopDrive` command.

This is for the NEO + SPARK MAX drivetrain and includes two parts: 
1. Writing the basic command for split arcade drive
2. Utilizing advanced features on the MC such as ramping

**Comment by tylertian123** [comment]
Some resources for working with SPARK MAXes: 
API Documentation: http://www.revrobotics.com/content/sw/max/sw-docs/SPARK-MAX-Java-API-Offline.pdf
API Javadocs: http://www.revrobotics.com/content/sw/max/sw-docs/java/com/revrobotics/SparkMax.html ~~(basically useless)~~
User's Manual: https://www.revrobotics.com/sparkmax-users-manual/
Java Examples: https://github.com/REVrobotics/SPARK-MAX-Examples/tree/master/Java

**Comment by tylertian123** [comment]
@AmberMLiu will be taking the basic arcade drive part.

**Comment by hossainrafiu** [comment]
Just to let everyone know, the Spark Max controller has built-in ramping.
Here are the methods for the CANSparkMax:
![image](https://user-images.githubusercontent.com/44447986/71943276-12dfdf00-318e-11ea-94da-d567ae4f041f.png)
