### ISSUE TITLE
Write Drivetrain subsystem class (Talon + CIM)

### ISSUE THREAD

**Issue by tylertian123** [Arctos6135/frc-2020#2]
Write code for the Drivetrain subsystem.

This is for the Talon SRX + CIM drivetrain.

**Comment by tylertian123** [comment]
@JeremyXie123 will be taking this.

**Comment by sadmanca** [comment]
Wrote drivetrain subsystem using Talon SRXs (needs review by another programmer). Have not written any code referring to CIMs.

**Comment by tylertian123** [comment]
Yup, sounds good. Yeah the CIMs don't matter; from the code's point of view, only the MC matters and the specific type of motor is not a concern. I will review the code soon. Good work!

**Comment by tylertian123** [comment]
I see, most of it looks good, I will make some comments on the commit.

**Comment by tylertian123** [comment]
The code looks good, although most likely we won't use it. This issue is now closed.

Once we're sure the code won't be used anymore, the branch will be merged into `develop` using the "ours" strategy so the contributions are still kept.
