### ISSUE TITLE
Write intake subsystem and teleop command

### ISSUE THREAD

**Issue by tylertian123** [Arctos6135/frc-2020#23]
The intake subsystem is close to being finalized. It will take some time to be built, but if you want some work to do, we can start writing controls for it now. (This is entirely optional for now.)

Here's the CAD for the intake we will be building:
![img](https://contattafiles.s3.us-west-1.amazonaws.com/tnt1555/qhCUmWwipEV7Qov/Screen%20Shot%202020-01-29%20at%2011.01.29%20PM.png)

There will be one motor to control the rollers (most likely brushed - go with Talon SRX for now if you're doing this), and one piston to control the raising and lowering of the intake. *The intake should always start raised so it fits inside the frame perimeter.* The raising/lowering should be a button for toggling, and the rollers can be controlled by either an analog trigger or button. *The intake controls should be on a separate operator controller - if not already defined, this will be a `new XboxController(1)`.*

If you want to work on this, please let me know. Otherwise, I will assign this or do it myself when the intake is closer to being done. 

P. S. Oops just realized I didn't teach pneumatics yet. It shouldn't be that hard. Ask me if you have any questions, but if you want an example of how it's done, you can look at the `pneumatic-prototype` branch.

**Comment by michal-davis** [comment]
Whatever input is used for activating the rollers, it should be able to go both ways (in and out) so we can both outtake and get the high bay idea at least tested. That likely means two inputs, since joystick is very silly for this.

**Comment by tylertian123** [comment]
@michal-davis Will it just be called "Intake" or should there be a name for it?

**Comment by tylertian123** [comment]
Also, we will most likely be using a double solenoid for this.

**Comment by tylertian123** [comment]
Good work, this issue is mostly done now. I just added some last comments, fix those and it should be ready to go. I also merged `develop` into `intake`.

**Comment by tylertian123** [comment]
@JeremyXie123, do you think the intake is done? if so I'll file a PR to merge it into `develop`, or you can do it yourself.

**Comment by JeremyXie123** [comment]
Go ahead, I don't want to break anything. I believe it is done, but we may have to revisit later if there's a problem.

**Comment by tylertian123** [comment]
@JeremyXie123, I'm remapping intake toggle to the A button so the B button can be used for motor overheat protection override for the shooter (to keep consistency with the driver controller's controls). Is that ok?

**Comment by tylertian123** [comment]
Also, the intake will be using a Victor SPX instead of a Talon SRX for the rollers (my bad). Since it's a small change, I'm going to make a direct commit to `develop` to fix this once you approve of the controls changes.

**Comment by tylertian123** [comment]
Perhaps I'll address #31 in that commit as well.

**Comment by JeremyXie123** [comment]
Go for it.
